services:

  catalog-service-1:
    build: ./CatalogReplica1
    ports:
      - "5001:5001"
    volumes:
      - ./CatalogReplica1/data:/app/data

  catalog-service-2:
    build: ./CatalogReplica2
    ports:
      - "5003:5001"
    volumes:
      - ./CatalogReplica2/data:/app/data

  order-service-1:
    build: ./OrderReplica1
    ports:
      - "5002:5002"
    volumes:
      - ./OrderReplica1:/app
      - /app/node_modules
    depends_on:
      - catalog-service-1
      - catalog-service-2

  order-service-2:
    build: ./OrderReplica2
    ports:
      - "5004:5002"
    volumes:
      - ./OrderReplica2:/app
      - /app/node_modules
    depends_on:
      - catalog-service-1
      - catalog-service-2

  frontend-service:
    build: ./FrontendService
    ports:
      - "5050:5000"
    depends_on:
      - catalog-service-1
      - catalog-service-2
      - order-service-1
      - order-service-2